---
- name: Configuring Cisco IOS Devices
  gather_facts: no
  hosts: routers
  connection: network_cli

  tasks:
    - name: Backup running-config
      ios_config:
        backup: yes
...
# Command to run:
# ansible-playbook -i ./ansible_sample_inventory_file ansible_playbook - ios_config_backup.yaml