---
- name: Configuring Cisco IOS Devices
  gather_facts: yes
  hosts: local_sw_1, local_sw_2, local_sw_3, local_sw_4
  connection: network_cli

  tasks:
    - name: Basic Configuration
      ios_config:
        save_when: modified
        lines:
          - hostname "{{inventory_hostname}}"
          - ip name-server 8.8.8.8
          - no ip http server
      register: output

    - name: Printing at the console
      debug: var=output
...
# Command to run:
# ansible-playbook -i ./inventory ios_basic_config.yaml
